image:
  repo: robotshop
  version: latest

redis:
  # Storage class to use with redis statefulset.
  storageClassName: standard

eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# For the mini ones minikube, minishift set to true
nodeport: false

payment:
  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  gateway: null
  #gateway: https://www.worldpay.com