apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cart.name }}
  labels:
    service: {{ .Values.cart.label }}
spec:
  replicas: {{ .Values.cart.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.cart.label }}
  template:
    metadata:
      labels:
        service: {{ .Values.cart.label }}
    spec:
      containers:
      - name: {{ .Values.cart.name }}
        image: "{{ .Values.cart.repo }}/cart:{{ .Values.cart.cart_version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: {{ .Values.cart.port }}
        resources:
          limits:
            cpu: {{ .Values.cart.cpu_limits }}
            memory: {{ .Values.cart.memory_limits }}
          requests:
            cpu: {{ .Values.cart.cpu_request }}
            memory: {{ .Values.cart.memory_request }}
