apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dispatch.name }}
  labels:
    service: {{ .Values.dispatch.label }}
spec:
  ClusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: {{ .Values.dispatch.label }}
