apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dispatch
  template:
    metadata:
      labels:
        service: dispatch
    spec:
      containers:
      - name: dispatch
        image: {{ .Values.image.repo }}/rs-dispatch:{{ .Values.image.version }}
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          limits:
            memory: "100Mi"
            cpu: "200m"
          requests:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
