apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
  labels:
    service: {{ .Values.mongodb.label }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.mongodb.label }}
  template:
    metadata:
      labels:
        service: {{ .Values.mongodb.label }}
    spec:
      containers:
      - name: {{ .Values.mongodb.name }}
        image: {{ .Values.image.repo }}/rs-mongodb:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # agent networking access usually useful for monitoring
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        resources:
          limits:
            cpu: {{ .Values.mongodb.cpu_limits }}
            memory: {{ .Values.mongodb.memory_limits }}
          requests:
            cpu: {{ .Values.mongodb.cpu_request }}
            memory: {{ .Values.mongodb.memory_request }}