apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.mongodb.label }}
  name: {{ .Values.mongodb.name }}
spec:
  selector:
    service: {{ .Values.mongodb.label }}
  ports:
  - name: {{ .Values.mongodb.port_name }}
    port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}