apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    service: mysql
spec:
  selector:
    matchLabels:
      service: mysql
  replicas: 1
  template:
    metadata:
      labels:
        service: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.image.repo }}/rs-mysql-db:{{ .Values.image.version}}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        resources:
            limits:
                cpu: 200m
                memory: 1024Mi
            requests:
                cpu: 100m
                memory: 700Mi