apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    service: {{ .Values.mysql.label }}
spec:
  selector:
    matchLabels:
      service: {{ .Values.mysql.label }}
  replicas: {{ .Values.mysql.replicas }}
  template:
    metadata:
      labels:
        service: {{ .Values.mysql.label }}
    spec:
      containers:
      - name: {{ .Values.mysql.name }}
        image: "{{ .Values.mysql.repo }}/mysql:{{ .Values.mysql.mysql_version}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
        resources:
            limits:
                cpu: {{ .Values.mysql.cpu_limits }}
                memory: {{ .Values.mysql.memory_limits }}
            requests:
                cpu: {{ .Values.mysql.cpu_request }}
                memory: {{ .Values.mysql.memory_request }}