apiVersion: v1
kind: Service
metadata:
  name: 
  labels:
    service: {{ .Values.mysql.label }}
  name: {{ .Values.mysql.name }}
spec:
  ports:
  - port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
    name: {{ .Values.mysql.port_name }}
  selector:
    service: {{ .Values.mysql.label }}