apiVersion: v1
kind: Service
metadata:
  name: 
  labels:
    service: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: tcp-amqp
  - port: 15672
    targetPort: 15672
    name: http-management
  - port: 4369
    targetPort: 4369
    name: tcp-epmd
  selector:
    service: rabbitmq