apiVersion: apps/v1
kind: Deployment
metadata: 
  name: shipping
  labels:
    service: shipping
spec:
  selector:
    matchLabels:
      service: shipping
  replicas: 1
  template:
    metadata:
      labels:
        service: shipping
    spec:
      containers:
      - name: shipping
        image: {{ .Values.image.repo }}/rs-shipping:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
            successThreshold: 1
        resources:
            limits:
                cpu: 200m
                memory: 1000Mi
            requests:
                cpu: 100m
                memory: 500Mi