apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shipping.name }}
  labels:
    service: {{ .Values.shipping.label }}
spec:
  ports:
  - port: {{ .Values.shipping.port }}
    targetPort: {{ .Values.shipping.port }}
    name: {{ .Values.shipping.port_name }}
  selector:
    service: {{ .Values.shipping.label }}