apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shipping.name }}
  labels:
    service: {{ .Values.shipping.label }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: {{ .Values.shipping.port_name }}
  selector:
    service: {{ .Values.shipping.label }}