apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.user.name }}
  labels:
    service: {{ .Values.user.label }}
spec:
  selector:
    matchLabels:
      service: {{ .Values.user.label }}
  replicas: 1
  template:
    metadata:
      labels:
        service: {{ .Values.user.label }}
    spec:
      containers:
      - name: {{ .Values.user.name }}
        image: {{ .Values.image.repo }}/rs-user:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          # agent networking access
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: {{ .Values.user.port }}
        resources:
            limits:
                cpu: {{ .Values.user.cpu_limits }}
                memory: {{ .Values.user.memory_limits }}
            requests:
                cpu: {{ .Values.user.cpu_request }}
                memory: {{ .Values.user.memory_request }}