apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  labels:
    service: {{ .Values.web.label }}
spec:
  ports:
  - name: {{ .Values.web.port_name }}
    port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
  selector:
    service: {{ .Values.web.label }}
  {{ if .Values.nodeport }}
  type: NodePort
  {{ else }}
  type: LoadBalancer
  {{ end }}