apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.web.name }}
  labels:
    service: {{ .Values.web.label }}
spec:
  selector:
    matchLabels:
      service: {{ .Values.web.label }}
  replicas: {{ .Values.web.replicas }}
  template:
    metadata:
      labels:
        service: {{ .Values.web.label }}
    spec:
      containers:
      - name: {{ .Values.web.name }}
        image: {{ .Values.web.repo }}/web:{{ .Values.web.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.eum.key }}
        env:
        - name: INSTANA_EUM_KEY
          value: {{ .Values.eum.key }}
        - name: INSTANA_EUM_REPORTING_URL
          value: {{ .Values.eum.url }}
        {{- end}}
        ports:
        - containerPort: {{ .Values.web.port }}
        resources:
            limits:
                cpu: {{ .Values.web.cpu_limits }}
                memory: {{ .Values.web.memory_limits }}
            requests:
                cpu: {{ .Values.web.cpu_request }}
                memory: {{ .Values.web.memory_request }}