name: cart

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '.github/workflow/cart.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.js'
      - '.github/workflow/cart.yaml'
jobs:
  cart:
    name: Build and deploy cart microservice
    runs-on: [self-hosted, linux] # Use a standard runner instead of self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install Dependencies
        run: npm install 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/cart:latest