name: cart

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '.github/workflow/cart.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.js'
      - '.github/workflow/cart.yaml'
jobs:
  cart:
    name: Build and deploy cart microservice
    runs-on: ubuntu-latest # Use a standard runner instead of self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install Dependencies
        run: npm install 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cart:latest

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push changes
      run: |
        git config --user.name "Saurabh Kaveri"
        git config --user.email "kaverisaurabh1998@gmail.com"
        git add K8s/helm/values.yaml
        git commit -m "Updated the dockerfile"
        git push 
