name: catalogue

on:
  push:
    paths:
      - '**.js'
      - .github/workflows/catalogue.yaml  # Triggered on push to JavaScript files or workflow changes

jobs:
  catalogue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning

      - name: Install Dependencies
        run: npm install
        working-directory: catalogue  # Specify directory for npm install

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: catalogue/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catalogue:${{ github.run_id }}  # Docker image tag with GitHub run ID

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: catalogue  # Wait for 'catalogue' job to complete successfully

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}  # Use token for repository access

      - name: Update new tag in helm chart
        run: |
          git config --global user.name "Saurabh Kaveri"
          git config --global user.email "kaverisaurabh1998@gmail.com"
          sed -i 's/version: .*/version: "{{ github.run_id }}"/' K8s/helm/values.yaml  # Update version in Helm values.yaml using GitHub run ID
          git add K8s/helm/values.yaml
          git commit -m "Update the tag in values file"
          git push origin main  # Push changes to the main branch

