name: dispatch

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - .github/workflows/dispatch.yaml
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - .github/workflows/dispatch.yaml

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: ^1.13.1
      id: go

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for accurate versioning

    - name: Install Dependencies
      run: go mod download
      working-directory: dispatch  # Run go mod download in the dispatch directory

    - name: Docker Build
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push 
      uses: docker/build-push-action@v6
      with:
        context: .  # Build context is the root directory
        file: dispatch/Dockerfile  # Path to the Dockerfile within the dispatch directory
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dispatch:{{ github.run_id }}  # Docker image tag with GitHub run ID

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}  # Use token for repository access

      - name: Update new tag in values yaml file
        run: |
          git config --global user.name "Saurabh Kaveri"
          git config --global user.email "kaverisaurabh1998@gmail.com"
          sed -i 's/version: .*/version: "{{ github.run_id }}"/' K8s/helm/values.yaml  # Update version in Helm values.yaml using GitHub run ID
          git add K8s/helm/values.yaml
          git commit -m "Updated the tag in values file"
          git push origin main  # Push changes to the main branch
