name: mongo

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - .github/workflows/mongo.yaml
  pull_request:
    branches:
      - main
    paths:
      - '**.js'
      - .github/workflows/mongo.yaml

jobs:
  mongo:
    runs-on: ubuntu-latest
    steps:
      - name: Configure nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm install mongodb
          cp mongo/**.js /docker-entrypoint-initdb.d/
        working-directory: mongo 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: mongo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: mongo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update the tags in value file
        run: |
          git config --global user.name "Saurabh Kaveri"
          git config --global user.email "kaverisaurabh1998@gmail.com"
          sed -i 's/version: .*/version: "{{ github.run_id }}"/' K8s/helm/values.yaml
          git add K8s/helm/values.yaml
          git commit -m "Update the tag values in values file"
          git push origin main
