name: mysql

on:
  push:
    branches:
      - main 
    paths:
      - '**.sql*'
      - .github/workflows/mysql.yaml
  pull_request:
    branches:
      - main 
    paths:
      - '**.sql*'
      - .github/workflows/mysql.yaml

jobs:
  mysql:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up a MySQL database
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"

      - name: Set executable permissions for config.sh
        run: |
          chmod +x mysql/config.sh
  
      - name: Install dependencies
        run: |
          sudo mkdir -p /docker-entrypoint-initdb.d/
          sudo cp -fr mysql/scripts/* /docker-entrypoint-initdb.d/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: mysql/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mysql:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: mysql
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update the tags in value file
        run: |
          git config --global user.name "Saurabh Kaveri"
          git config --global user.email "kaverisaurabh1998@gmail.com"
          sed -i 's/version: .*/version: "${{ github.run_id }}"/' K8s/helm/values.yaml
          git add K8s/helm/values.yaml
          git commit -m "Update the tag values in values file"
          git push origin main

