name: payment

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/payment.yaml
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/payment.yaml

jobs:
  payment:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5 
        with:
          python-version: 'pypy3.9'
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: install dependencies
        run: python -m pip install -r requirements.txt
        working-directory: payment

    
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: payment/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/payment:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: payment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update the tags in values file 
        run: |
          git config --global user.name "Saurabh Kaveri"
          git config --global user.email "kaverisaurabh1998@gmail.com"
          sed -i 's/version: .*/version: "${{ github.run_id }}"/' K8s/helm/values.yaml
          git add K8s/helm/values.yaml
          git commit -m "Update the tags in values file"
          git push origin main






